import os
import sys
from google import genai

# ۱. تنظیمات API Key
api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    print("Error: GEMINI_API_KEY is not set in GitHub Secrets.")
    sys.exit(1)

# ۲. دریافت سوال
user_question = sys.argv[1] if len(sys.argv) > 1 else "Hello!"

# ۳. متصل شدن به کلاینت گوگل
client = genai.Client(api_key=api_key)

try:
    # ۴. استفاده از مدل Gemini 3 Flash Preview طبق درخواست شما
    # نام مدل دقیقاً از لیستی که فرستادید استخراج شده است
    response = client.models.generate_content(
        model="gemini-3-flash-preview", 
        contents=user_question
    )
    
    answer = response.text

    # ۵. ذخیره پاسخ در فایل
    filename = "gemini_response.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# 🤖 Gemini 3 Response\n\n")
        f.write(f"### ❓ Question:\n> {user_question}\n\n")
        f.write(f"### 💡 Answer:\n{answer}\n\n")
        f.write(f"---\n*Generated by GitHub Actions using Gemini 3 Flash Preview*")
    
    print(f"Successfully saved to {filename}")

except Exception as e:
    print(f"An error occurred: {e}")
    sys.exit(1)
