import os
import sys
from google import genai

# ۱. تنظیمات API Key
api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    print("Error: GEMINI_API_KEY is not set in GitHub Secrets.")
    sys.exit(1)

# ۲. دریافت سوال از گیت‌هاب اکشن
if len(sys.argv) < 2:
    user_question = "Hello Gemini! How are you?"
else:
    user_question = sys.argv[1]

# ۳. متصل شدن به کلاینت گوگل
client = genai.Client(api_key=api_key)

try:
    # ۴. ارسال درخواست به مدل (استفاده از مدل انتخابی از لیست شما)
    # مدل gemini-2.0-flash انتخاب شد چون رایگان و سریع است
    response = client.models.generate_content(
        model="gemini-2.0-flash", 
        contents=user_question
    )
    
    answer = response.text

    # ۵. ذخیره پاسخ در فایل Markdown برای نمایش در گیت‌هاب
    filename = "gemini_response.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# 🤖 Gemini Response\n\n")
        f.write(f"### ❓ Question:\n> {user_question}\n\n")
        f.write(f"### 💡 Answer:\n{answer}\n\n")
        f.write(f"---\n*Generated by GitHub Actions using Gemini 2.0 Flash*")
    
    print(f"Successfully saved to {filename}")

except Exception as e:
    print(f"An error occurred: {e}")
    sys.exit(1)
